### ISSUE TITLE
Context not being reset between requests

### ISSUE THREAD

**Issue by mark-anders** [jarus/flask-testing#105]
My tests typically require making a number of requests to my app, and what I'm seeing is that within my app, variables attached to Flask's g are retained across requests.

I believe the problem is due to the fact that the `self._ctx.push()` is called in `self._pre_setup()` prior to the test case being run and then `self._ctx.pop()` is called after the test case runs in `self._post_teardown()`. This appears to keep the context around for the duration of the test case, rather than allowing it to be scoped to the request.

Commenting out these 2 calls fixes the problem for me. 

I'm not sure if this is related to #38 since I'm not doing anything with templates, but context variables sticking to the first request sounds like the same thing.

**Comment by jcomo** [comment]
Thanks for bringing this issue up @mark-anders. Take a look at this PR and let me know what you think https://github.com/jarus/flask-testing/pull/108

**Comment by mark-anders** [comment]
Hi @jcomo , sorry for the delay in responding.  This looks great. It's basically the same changes I had made to get things to work.  Thank you!

**Comment by i-am-david-fernandez** [comment]
Hi @jcomo. Am I correct in understanding that, as the fix for this (#108) has been reverted (e.g., #118), this is still an open issue? I'm having problems that I believe are essentially the same as this issue describes (primary symptom being that `flask.g` persists across requests within a test case).

More details: The test in question is testing user login/logout, which uses `WTForms` via `Flask-WTF`. My logout view method clears the session, removing the WTF `csrf_token` session variable, but during testing the `flask.g.csrf_token` persists. My shallow understanding of `WTForms` is that, when a form is created, the session variable is created if it doesn't exist, but only if the `flask.g` variable also does not exist. The first time through everything is fine, but subsequent login attempts (within a single test case) fail because, while the session `csrf_token` has been removed, `flask.g.csrf_token` has persisted (across requests, within the test case), and so a new session token is not created and so the login form fails validation.

I'm using `flask-testing` `0.7.1` via `anaconda` in Windows.

**Comment by i-am-david-fernandez** [comment]
More info: Removing the context push/pop (as per https://github.com/jarus/flask-testing/issues/105#issue-216985085) fixes the issue (though introduces other problems in other tests, though these can be corrected with explicit context pushing/popping in those cases' setup/teardown).

**Comment by jcomo** [comment]
That's correct; it is still an open issue. The behavior is broken right now but unfortunately many people who use the library have relied on this broken behavior in one way or another and "fixing" it in fact broke many tests.

As a workaround, you can subclass the TestCase class provided by the library and do that in your setup/teardown functions and inherit from that everywhere instead. For future versions, I am considering deprecating the old behavior (but providing an option in the meantime to keep it) and then removing it altogether in a major version bump. Open to ideas though
