### ISSUE TITLE
assertRedirects makes wrong assumptions

### ISSUE THREAD

**Issue by Diaoul** [jarus/flask-testing#52]
https://github.com/jarus/flask-testing/blob/master/flask_testing/utils.py#L209

This suppose you run test with localhost. In case one use subdomains, this doesn't work because subdomains required a FQDN like `myserver.local`.

**Comment by jcomo** [comment]
I was looking at the PR and saw that it was closed because the location would be untested if not provided. I agree with the comment based on the implementation in the PR but I think there's still something we can do to solve this issue.

I wouldn't want to break backwards compatibility with those who are relying on the check against a relative path by all of a sudden requiring a full URL. I propose that the location can either be a relative path (which would be relative to `SERVER_NAME` in config) OR it could be a full URL. To do the check we would have to detect the difference. What do you think?
