### ISSUE TITLE
How to test with route decorators

### ISSUE THREAD

**Issue by jhorneman** [jarus/flask-testing#64]
Not an issue, more of a question.

My Flask apps tend to use route decorators (not all of them in blueprints), which means they use a global app object. My create_app function imports my view module. But if that create_app function is called more than once, as it is in Flask-Testing, the views import only works once and my routes aren't picked up.

What's the recommended way of combining route decorators with Flask-Testing?

Thanks.

**Comment by jcomo** [comment]
From your explanation, its hard to tell why the views only being imported once will cause the routes to not be picked up since those imports should be cached and it behave the same way the second time around. Your suggestion of returning the same instance every time is perfectly acceptable in the case of app factories (as it sounds like you have). When running the server, I assume its only created once so it makes sense to mirror that throughout the duration of your test run

**Comment by jhorneman** [comment]
I had to think hard to remember what my question was about :)

> Your suggestion of returning the same instance every time is perfectly acceptable in the case of app factories (as it sounds like you have). When running the server, I assume its only created once so it makes sense to mirror that throughout the duration of your test run

Well, sorta kinda. It assumes the app instance is never modified by a test. If would be bad if tests affect other tests.

I seem to have solved this problem enough that I can work with it (so I'll close the issue), although I'm not using Flask-testing. I've even found a way around Flask's insistence of using decorators that refer to global variables, which has always annoyed me a tiny bit :)

**Comment by jcomo** [comment]
Sorry about the incredibly long wait haha. I stepped on board to help maintain since this project was becoming slightly abandoned.

Good point about tests affecting other tests. The way around that would be to have a way to tear down the app if is was created in between tests but I understand thats sometimes easier said than done

**Comment by jhorneman** [comment]
No problem :) I found a way around it. I think I may even have tried setting up the app every time, but it was very slow.
