### ISSUE TITLE
Signals not supported raised 

### ISSUE THREAD

**Issue by maxtortime** [jarus/flask-testing#99]
When I'm using `assert_template_used` method in my test case.
It raised below exception.
`RuntimeError: Signals not supported`.

But after I installed [blinker](https://pypi.python.org/pypi/blinker) this exception have not raised.

I think you should add `blinker` to `setup.py`.

Regrads
Taehwan Kim

**Comment by jcomo** [comment]
The reason blinker is not included in the package is because blinker is meant to be optional for a flask installation. Therefore, flask-testing will not complain until you try to use functionality that is required by blinker (in this case, `assert_template_used`). Maybe a more descriptive error message would be better in this case

**Comment by maxtortime** [comment]
I understand, Above I mentioned, after installing `blinker` my test case works normally.
I think document supplement is more helpful. Before using `assert_template_used`, document tells installing  `blinker` to user will be better.
